### ISSUE TITLE
[AWS] Allow functions to force non-HTTP mode

### ISSUE THREAD

**Issue by justinedelson** [adobe/helix-universal#296]
**Is your feature request related to a problem? Please describe.**

The way that helix-universal detects that the response should be returned as-is is based on the absence of `event.requestContext` (see https://github.com/adobe/helix-universal/blob/5eb09fc6a564e81111db2616bea195348a2ec49e/src/aws-adapter.js#L87). However, this does not work properly when a function is used as an API Gateway Authorizer.

When used as an Authorizer, `event.requestContext` **is** set. But the response needs to be returned in the raw form provided by helix-universal when `nonHttp` is `true`.

**Describe the solution you'd like**

Allow functions to explicitly ask for non-HTTP mode to be used in the response by setting a header, e.g. `force-non-http: true`

**Describe alternatives you've considered**

Not using helix-universal for this use case but that would create other problems.

**Additional context**

**Comment by tripodsan** [comment]
you can just use the `adapterFile` parameter to create a non-universal function:
https://github.com/adobe/helix-token-authorizer/blob/d7f95a8770fb041cf2216bee262cb0ae6dede96d/package.json#L24

**Comment by justinedelson** [comment]
@tripodsan that can work but adds a bit of complexity since I also want the authorizer lambda to support [helix-status](https://github.com/adobe/helix-status) and potentially also [helix-shared-secrets](https://github.com/adobe/helix-shared/tree/main/packages/helix-shared-secrets). Doable but I'm concerned that at some point I'm going to be duplicating the construction of the `UniversalContext`.

**Comment by tripodsan** [comment]
@justinedelson ok. valid point. I'm not happy with the mechanism.... I'll comment in the PR
