### ISSUE TITLE
Catch SyntaxError and return 400 as well

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-universal#82]
In:

https://github.com/adobe/helix-universal/blob/85e54e625849ab54f5710ddd710340a9a11a90de/src/aws-adapter.js#L110-L121

we could additionally check whether `e` is of type `SyntaxError`, which would indicate that JSON parsing of the request body failed in `body-data-wrapper.js` (see https://github.com/adobe/helix-shared/issues/593)

Potential downside: some genuine parsing problem elsewhere in the code might be treated as bad request.

**Comment by dominique-pfister** [comment]
Note that this would fix https://github.com/adobe/helix-shared/issues/593

**Comment by tripodsan** [comment]
I don't think this should be handled here.... if the `SyntaxError` is thrown where no input-data is involved, i.e. reading from a backend, a `500` would be more appropriate.

**Comment by dominique-pfister** [comment]
Closing as it is now fixed in https://github.com/adobe/helix-shared/issues/593
